import Spiderman from "../../images/image 4.png";
import PS5Controller from "../../images/ps5Controller.png";

export const productsdata = [
  {
    product_id: 1,
    product_title: "Spiderman - Miles Morales",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: Spiderman.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.8573,
  },
  {
    product_id: 2,
    product_title: "PS5 Controller",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: PS5Controller.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.78332,
  },
  {
    product_id: 3,
    product_title: "Spiderman - Miles Morales",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: Spiderman.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.8573,
  },
  {
    product_id: 4,
    product_title: "PS5 Controller",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: PS5Controller.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.78332,
  },
  {
    product_id: 5,
    product_title: "Spiderman - Miles Morales",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: Spiderman.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.8573,
  },
  {
    product_id: 6,
    product_title: "PS5 Controller",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: PS5Controller.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.78332,
  },
  {
    product_id: 7,
    product_title: "Spiderman - Miles Morales",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: Spiderman.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.8573,
  },
  {
    product_id: 8,
    product_title: "PS5 Controller",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: PS5Controller.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.78332,
  },
  {
    product_id: 9,
    product_title: "Spiderman - Miles Morales",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: Spiderman.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.8573,
  },
  {
    product_id: 10,
    product_title: "PS5 Controller",
    product_oldprice: 16999,
    product_newprice: 12999,
    product_description:
      "Experience The Rise Of Miles Morales As The New Hero Masters Incredible, Explosive New Powers To Become His Own Spider-Man.",
    product_image: PS5Controller.src,
    product_genre: ["Action", "Thriller", "Story"],
    product_platform: "ps4",
    product_condition: "used",
    product_weight: 0.78332,
  },
];
